require("dotenv").config()

module.exports = {
    JWT_SECRET: process.env.JWT_SECRET,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_PORT: process.env.EMAIL_PORT,
    EMAIL_USER: process.env.EMAIL_USER,
    EMAIL_PASS: process.env.EMAIL_PASS,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_SECRET: process.env.CLOUDINARY_SECRET,


    FIREBASE_TYPE:process.env.FIREBASE_TYPE,
    FIREBASE_PROJECTID:process.env.FIREBASE_PROJECTID,
    FIREBASE_PRIVATE_KEY_ID:process.env.FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY:process.env.FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL : process.env.FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID : process.env.FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URL : process.env.FIREBASE_AUTH_URL,
    FIREBASE_TOKEN_URL : process.env.FIREBASE_TOKEN_URL,
    FIREBASE_AUTH_PROVIDER_x509_CERT_URL : process.env.FIREBASE_AUTH_PROVIDER_x509_CERT_URL,
    FIREBASE_CLIENT_x509_CERT_URL:process.env.FIREBASE_CLIENT_x509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN : process.env.FIREBASE_UNIVERSE_DOMAIN,

    SERVER_PORT:process.env.PORT,
    DB_URL:process.env.DB_URL,

    MONGO_URL:process.env.MONGO_URL,

    FRONTEND_URL:process.env.FRONTEND_URL

}